apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "upcloud-csi.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "upcloud-csi.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "upcloud-csi.fullname" . }}
  replicas: {{ .Values.controller.replicas }}
  {{- if .Values.controller.minReadySeconds }}
  minReadySeconds: {{ .Values.controller.minReadySeconds }}
  {{- end }}
  {{- if .Values.controller.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.controller.revisionHistoryLimit }}
  {{- end }}
  {{- with .Values.controller.updateStrategy }}
  updateStrategy:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "upcloud-csi.selectorLabels" . | nindent 6 }}
      app: {{ include "upcloud-csi.fullname" . }}-controller
  template:
    metadata:
      labels:
        {{- include "upcloud-csi.selectorLabels" . | nindent 8 }}
        app: {{ include "upcloud-csi.fullname" . }}-controller
        role: csi-upcloud
{{- with .Values.controller.podLabels }}
{{ tpl (toYaml .) $ | indent 8 }}
{{- end }}
      annotations:
        checksum/credentials: {{ include "upcloud-csi.credentialsChecksum" . | quote }}
{{- with .Values.controller.podAnnotations }}
{{ tpl (toYaml .) $ | indent 8 }}
{{- end }}
    spec:
      priorityClassName: {{ .Values.controller.priorityClassName }}
      serviceAccountName: {{ .Values.controller.serviceAccountName | default (printf "%s-controller" (include "upcloud-csi.fullname" .)) }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.controller.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.controller.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.runtimeClassName }}
      runtimeClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.controller.dnsPolicy }}
      dnsPolicy: {{ . | quote }}
      {{- end }}
      {{- with .Values.controller.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: csi-provisioner
          image: "{{ .Values.controller.sidecars.csiProvisioner.repository }}:{{ .Values.controller.sidecars.csiProvisioner.tag }}"
          imagePullPolicy: {{ .Values.controller.sidecars.csiProvisioner.pullPolicy }}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v={{ .Values.controller.logLevel | default .Values.logLevel }}"
            - "--timeout=600s"
            {{- if .Values.metrics.enabled }}
            - "--http-endpoint=:8080"
            {{- end }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          {{- with .Values.controller.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          {{- with .Values.controller.sidecars.csiProvisioner.resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- if .Values.metrics.enabled }}
          ports:
            - containerPort: 8080
              name: prov-metrics
              protocol: TCP
          {{- end }}
        - name: csi-attacher
          image: "{{ .Values.controller.sidecars.csiAttacher.repository }}:{{ .Values.controller.sidecars.csiAttacher.tag }}"
          imagePullPolicy: {{ .Values.controller.sidecars.csiAttacher.pullPolicy }}
          args:
            - "--v={{ .Values.controller.logLevel | default .Values.logLevel }}"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=600s"
            {{- if .Values.metrics.enabled }}
            - "--http-endpoint=:8081"
            {{- end }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          {{- with .Values.controller.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          {{- with .Values.controller.sidecars.csiAttacher.resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- if .Values.metrics.enabled }}
          ports:
            - containerPort: 8081
              name: att-metrics
              protocol: TCP
          {{- end }}
        - name: csi-resizer
          image: "{{ .Values.controller.sidecars.csiResizer.repository }}:{{ .Values.controller.sidecars.csiResizer.tag }}"
          imagePullPolicy: {{ .Values.controller.sidecars.csiResizer.pullPolicy }}
          args:
            - "--v={{ .Values.controller.logLevel | default .Values.logLevel }}"
            - "--timeout=600s"
            - "--csi-address=$(ADDRESS)"
            - "--handle-volume-inuse-error=true"
            {{- if .Values.metrics.enabled }}
            - "--http-endpoint=:8082"
            {{- end }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          {{- with .Values.controller.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          {{- with .Values.controller.sidecars.csiResizer.resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- if .Values.metrics.enabled }}
          ports:
            - containerPort: 8082
              name: res-metrics
              protocol: TCP
          {{- end }}
        - name: csi-snapshotter
          image: "{{ .Values.controller.sidecars.csiSnapshotter.repository }}:{{ .Values.controller.sidecars.csiSnapshotter.tag }}"
          imagePullPolicy: {{ .Values.controller.sidecars.csiSnapshotter.pullPolicy }}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v={{ .Values.controller.logLevel | default .Values.logLevel }}"
            - "--timeout=600s"
            - "--leader-election=false"
            {{- if .Values.metrics.enabled }}
            - "--http-endpoint=:8083"
            {{- end }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          {{- with .Values.controller.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          {{- with .Values.controller.sidecars.csiSnapshotter.resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- if .Values.metrics.enabled }}
          ports:
            - containerPort: 8083
              name: snap-metrics
              protocol: TCP
          {{- end }}
        - name: csi-upcloud-plugin
          image: {{ include "upcloud-csi.driverImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodehost=$(NODE_ID)"
            - "--mode=monolith"
            - "--address=tcp://0.0.0.0:13071"
            {{- if .Values.metrics.enabled }}
            - "--metrics-address=tcp://0.0.0.0:8090"
            {{- end }}
          env:
            - name: CSI_ENDPOINT
              value: "unix:///var/lib/csi/sockets/pluginproxy/csi.sock"
            - name: UPCLOUD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "upcloud-csi.credentialsSecret" . }}
                  key: {{ .Values.credentials.usernameKey }}
            - name: UPCLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "upcloud-csi.credentialsSecret" . }}
                  key: {{ .Values.credentials.passwordKey }}
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- with .Values.controller.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 13071
              name: health
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - containerPort: 8090
              name: csi-metrics
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 13071
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 13071
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            {{- with .Values.controller.additionalVolumeMounts }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.controller.lifecycle }}
          lifecycle:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
      volumes:
        - name: socket-dir
          emptyDir: {}
        {{- with .Values.controller.additionalVolumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
