apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "upcloud-csi.fullname" . }}-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "upcloud-csi.labels" . | nindent 4 }}
spec:
  {{- if .Values.node.minReadySeconds }}
  minReadySeconds: {{ .Values.node.minReadySeconds }}
  {{- end }}
  {{- if .Values.node.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.node.revisionHistoryLimit }}
  {{- end }}
  {{- with .Values.node.updateStrategy }}
  updateStrategy:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "upcloud-csi.selectorLabels" . | nindent 6 }}
      app: {{ include "upcloud-csi.fullname" . }}-node
  template:
    metadata:
      labels:
        {{- include "upcloud-csi.selectorLabels" . | nindent 8 }}
        app: {{ include "upcloud-csi.fullname" . }}-node
        role: csi-upcloud
{{- with .Values.node.podLabels }}
{{ tpl (toYaml .) $ | indent 8 }}
{{- end }}
      annotations:
{{- with .Values.node.podAnnotations }}
{{ tpl (toYaml .) $ | indent 8 }}
{{- end }}
    spec:
      priorityClassName: {{ .Values.node.priorityClassName }}
      serviceAccountName: {{ .Values.node.serviceAccountName | default (printf "%s-node" (include "upcloud-csi.fullname" .)) }}
      hostNetwork: true
      {{- with .Values.node.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.node.tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.node.affinity }}
      affinity:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.node.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.node.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.node.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.node.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.node.runtimeClassName }}
      runtimeClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.node.dnsPolicy }}
      dnsPolicy: {{ . | quote }}
      {{- end }}
      {{- with .Values.node.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: csi-node-driver-registrar
          image: "{{ .Values.node.sidecars.csiNodeDriverRegistrar.repository }}:{{ .Values.node.sidecars.csiNodeDriverRegistrar.tag }}"
          imagePullPolicy: {{ .Values.node.sidecars.csiNodeDriverRegistrar.pullPolicy }}
          args:
            - "--v={{ .Values.node.logLevel | default .Values.logLevel }}"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/{{ .Values.csiDriver.name }}/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- with .Values.node.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
            - name: registration-dir
              mountPath: /registration/
          {{- with .Values.node.sidecars.csiNodeDriverRegistrar.resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
        - name: csi-upcloud-plugin
          image: {{ include "upcloud-csi.driverImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodehost=$(NODE_ID)"
            - "--mode=node"
            {{- $zone := .Values.node.zone | default .Values.controller.zone }}
            {{- if $zone }}
            - "--zone={{ $zone }}"
            {{- end }}
            - "--address=tcp://0.0.0.0:13071"
            {{- if .Values.metrics.enabled }}
            - "--metrics-address=tcp://0.0.0.0:8090"
            {{- end }}
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- with .Values.node.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.node.resources }}
          resources:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 13071
              name: health
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - containerPort: 8090
              name: csi-metrics
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 13071
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 13071
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
            {{- with .Values.node.additionalVolumeMounts }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.node.lifecycle }}
          lifecycle:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/{{ .Values.csiDriver.name }}
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
        {{- with .Values.node.additionalVolumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
