{{- if .Values.credentials.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "upcloud-csi.labels" . | nindent 4 }}
stringData:
  {{ .Values.credentials.tokenKey }}: {{ required "credentials.token is required when createSecret is true" .Values.credentials.token }}
{{- end }}
