{{- if .Values.credentials.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "upcloud-csi.labels" . | nindent 4 }}
stringData:
  {{ .Values.credentials.usernameKey }}: {{ required "credentials.username is required when createSecret is true" .Values.credentials.username }}
  {{ .Values.credentials.passwordKey }}: {{ required "credentials.password is required when createSecret is true" .Values.credentials.password }}
{{- end }}
