apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "upcloud-csi.fullname" . }}-snapshot-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "upcloud-csi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.snapshotController.replicas }}
  minReadySeconds: {{ .Values.snapshotController.minReadySeconds }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "upcloud-csi.selectorLabels" . | nindent 6 }}
      app: {{ include "upcloud-csi.fullname" . }}-snapshot-controller
  template:
    metadata:
      labels:
        {{- include "upcloud-csi.selectorLabels" . | nindent 8 }}
        app: {{ include "upcloud-csi.fullname" . }}-snapshot-controller
    spec:
      serviceAccountName: {{ .Values.controller.serviceAccountName | default (printf "%s-controller" (include "upcloud-csi.fullname" .)) }}
      priorityClassName: {{ .Values.snapshotController.priorityClassName }}
      {{- with .Values.snapshotController.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.snapshotController.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.snapshotController.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: snapshot-controller
          image: "{{ .Values.snapshotController.image.repository }}:{{ .Values.snapshotController.image.tag }}"
          imagePullPolicy: {{ .Values.snapshotController.image.pullPolicy }}
          args:
            - "--v={{ .Values.snapshotController.logLevel | default .Values.logLevel }}"
            - "--leader-election=true"
            - "--http-endpoint=:8080"
          {{- with .Values.snapshotController.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5

