{{- if .Values.storageClasses.enabled }}
{{- range .Values.storageClasses.classes }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .isDefault | quote }}
parameters:
  {{- if .tier }}
  tier: {{ .tier }}
  {{- end }}
  {{- if .type }}
  type: {{ .type }}
  {{- end }}
  {{- if .encryption }}
  encryption: {{ .encryption }}
  {{- end }}
provisioner: {{ $.Values.csiDriver.name }}
allowVolumeExpansion: {{ .allowVolumeExpansion }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- end }}
{{- end }}