apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.volumeSnapshotClass.name }}
  labels:
    {{- include "upcloud-csi.labels" . | nindent 4 }}
driver: {{ .Values.csiDriver.name }}
deletionPolicy: {{ .Values.volumeSnapshotClass.deletionPolicy }}
