version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      kubernetes:
        patterns:
          - k8s.io/*
      grpc:
        patterns:
          - google.golang.org/grpc
          - google.golang.org/genproto

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cmd/upcloud-csi-plugin
    schedule:
      interval: daily
