repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.12.2
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: test
        name: test
        language: system
        entry: make
        args: ["test"]
        pass_filenames: false
      - id: kube-lint
        name: kube-lint
        language: system
        entry: make
        args: ["kube-lint"]
        pass_filenames: false
        files: ^deploy/helm/
      - id: k8s-lint
        name: k8s-lint
        language: system
        entry: make
        args: ["k8s-lint"]
        pass_filenames: false
        files: ^deploy/helm/
