FROM alpine:3.20

LABEL org.opencontainers.image.source=https://github.com/upcloud-tools/upcloud-csi
LABEL org.opencontainers.image.description="UpCloud CSI Driver"

RUN apk add ca-certificates \
    cloud-utils-growpart \
    e2fsprogs \
    eudev \
    findmnt \
    xfsprogs \
    blkid \
    e2fsprogs-extra \
    util-linux \
    parted

ADD upcloud-csi-plugin /bin/

ENTRYPOINT ["/bin/upcloud-csi-plugin"]