apiVersion: v2
name: upcloud-csi
description: CSI driver for UpCloud block storage
type: application
version: "1.6.0"
appVersion: "v2.6.1"
kubeVersion: ">=1.21.0"
keywords:
  - csi
  - storage
  - upcloud
  - kubernetes
home: https://github.com/upcloud-tools/upcloud-csi
sources:
  - https://github.com/upcloud-tools/upcloud-csi
maintainers:
  - name: Leonardo (aardbol)
    url: https://github.com/aardbol
annotations:
  artifacthub.io/maintainers: |
    - name: aardbol
  artifacthub.io/category: storage
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Support
      url: https://github.com/upcloud-tools/upcloud-csi/issues
  artifacthub.io/changes: |
    - "Add networkPolicy resources for controller, node, snapshot-controller, and webhook"
    - "E2E test for network policy ingress enforcement"
