apiVersion: v2
name: upcloud-csi
description: CSI driver for UpCloud block storage with additional features like online volume resizing and ReadWriteMany storage (NFS)
type: application
version: "1.18.0"
appVersion: "v3.5.0"
kubeVersion: ">=1.31.0"
keywords:
  - csi
  - storage
  - upcloud
  - kubernetes
home: https://github.com/upcloud-tools/upcloud-csi
sources:
  - https://github.com/upcloud-tools/upcloud-csi
maintainers:
  - name: Leonardo (aardbol)
    url: https://github.com/aardbol
annotations:
  artifacthub.io/maintainers: |
    - name: aardbol
  artifacthub.io/category: storage
  artifacthub.io/crds: |
    - kind: VolumeSnapshotClass
      version: v1
      name: volumesnapshotclasses.snapshot.storage.k8s.io
      displayName: VolumeSnapshotClass
      description: VolumeSnapshotClass specifies parameters that a underlying storage system uses when creating a volume snapshot.
    - kind: VolumeSnapshotContent
      version: v1
      name: volumesnapshotcontents.snapshot.storage.k8s.io
      displayName: VolumeSnapshotContent
      description: VolumeSnapshotContent represents the actual on-disk snapshot object in the underlying storage system.
    - kind: VolumeSnapshot
      version: v1
      name: volumesnapshots.snapshot.storage.k8s.io
      displayName: VolumeSnapshot
      description: VolumeSnapshot is a user's request for either creating a point-in-time snapshot of a persistent volume, or binding to a pre-existing snapshot.
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Support
      url: https://github.com/upcloud-tools/upcloud-csi/issues
  artifacthub.io/changes: |
    - kind: changed
      description: Lower minimum kubeVersion to >=1.31.0 to widen supported Kubernetes versions
