name: Build image

on:
  push:
    branches: ["main"]
    paths:
      - "internal/**"
      - "cmd/**"
      - "go.mod"
      - "go.sum"

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-image:
    uses: ./.github/workflows/_reusable-build.yaml
    with:
      tags: ${{ github.sha }}
    secrets: inherit
