name: Dependency Review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    uses: upcloud-tools/gha-actions/.github/workflows/dependency-review.yaml@070918b27e20a6bd320cc93b569d912b1a227a6c
    secrets: inherit
