name: Dependency Review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    uses: upcloud-tools/gha-actions/.github/workflows/dependency-review.yaml@1dd7497095dbde7e8ae1b5f2afdad0a388821b74
    secrets: inherit
