name: build

on:
  push:
    branches: ["main"]
    tags: ["v*"]

env:
  GO_VERSION: '1.26'

jobs:
  build-image:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      image_name: ghcr.io/${{ github.repository }}
      tags: |
        ${{ github.ref_name }}
        ${{ startsWith(github.ref, 'refs/tags/') && 'latest' || '' }}
        ${{ github.ref_type != 'tag' && github.sha || '' }}
      go_version: ${{ env.GO_VERSION }}
    secrets: inherit
