name: Lint Golang

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - '.github/workflows/lint-golang.yaml'
  pull_request:

env:
  GO_VERSION: '1.26.5'

permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'
              - go.mod
              - go.sum
              - '.github/workflows/lint-golang.yaml'

      - if: steps.filter.outputs.go == 'true'
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - if: steps.filter.outputs.go == 'true'
        name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
          args: --timeout 5m
