name: Helm Lint

on:
  pull_request:
    paths:
      - 'deploy/helm/**'
      - '.github/workflows/lint-helm.yaml'
      - '.github/workflows/lint-golang.yaml'

jobs:
  helm-lint:
    name: helm-lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout head
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run helm lint
        run: make helm-lint

      - name: Render Helm chart
        run: helm template test-release deploy/helm/ > /tmp/rendered-chart.yaml

      - name: Run kube-linter
        uses: stackrox/kube-linter-action@87802a2f4e01abebb3ee3c67a3002fea71f6eae5 # v1.0.7
        with:
          directory: deploy/helm
          config: deploy/helm/.kube-linter.yaml
          format: plain

      - name: Run kubeconform
        uses: aardbol/k8s-lint@02ccb533796f0d15bdc78ad4acd9055995615a5e # v4.1.0
        with:
          manifests: /tmp/rendered-chart.yaml
          lintType: kubeconform
          kubeconformOpts: -summary -strict
