name: Lint Golang

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - '.github/workflows/lint-golang.yaml'
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - '.github/workflows/lint-golang.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  golangci-lint:
    uses: upcloud-tools/gha-actions/.github/workflows/lint-golang.yaml@070918b27e20a6bd320cc93b569d912b1a227a6c
