name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - deploy/helm/Chart.yaml
  workflow_dispatch:
    inputs:
      skip-e2e:
        description: Skip e2e tests
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: read

jobs:
  detect:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    outputs:
      skip: ${{ steps.detect.outputs.app_release_exists }}
      app_version: ${{ steps.detect.outputs.app_version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - id: detect
        uses: ./.github/actions/detect-versions

  build-image:
    needs: detect
    if: ${{ needs.detect.outputs.skip == 'false' }}
    uses: ./.github/workflows/_reusable-build.yaml
    with:
      tags: ${{ github.sha }}
    secrets: inherit
    permissions:
      contents: read
      packages: write

  e2e-1-31:
    needs: [detect, build-image]
    if: needs.detect.outputs.skip == 'false' && !inputs['skip-e2e']
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.31"
      image_tag: ${{ github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_31 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_31 }}

  e2e-1-32:
    needs: [detect, build-image]
    if: needs.detect.outputs.skip == 'false' && !inputs['skip-e2e']
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.32"
      image_tag: ${{ github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_32 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_32 }}

  e2e-1-33:
    needs: [detect, build-image]
    if: needs.detect.outputs.skip == 'false' && !inputs['skip-e2e']
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.33"
      image_tag: ${{ github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_33 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_33 }}

  e2e-1-34:
    needs: [detect, build-image]
    if: needs.detect.outputs.skip == 'false' && !inputs['skip-e2e']
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.34"
      image_tag: ${{ github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_34 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_34 }}

  e2e-1-35:
    needs: [detect, build-image]
    if: needs.detect.outputs.skip == 'false' && !inputs['skip-e2e']
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.35"
      image_tag: ${{ github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_35 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_35 }}

  release:
    needs: [detect, build-image, e2e-1-31, e2e-1-32, e2e-1-33, e2e-1-34, e2e-1-35]
    if: >-
      always() &&
      needs.detect.outputs.skip == 'false' &&
      needs.build-image.result == 'success' &&
      (needs.e2e-1-31.result == 'success' || needs.e2e-1-31.result == 'skipped') &&
      (needs.e2e-1-32.result == 'success' || needs.e2e-1-32.result == 'skipped') &&
      (needs.e2e-1-33.result == 'success' || needs.e2e-1-33.result == 'skipped') &&
      (needs.e2e-1-34.result == 'success' || needs.e2e-1-34.result == 'skipped') &&
      (needs.e2e-1-35.result == 'success' || needs.e2e-1-35.result == 'skipped')
    uses: upcloud-tools/gha-actions/.github/workflows/release-container.yaml@c0df829cbad57268497db8cfb6174419f925b283
    with:
      app_version: ${{ needs.detect.outputs.app_version }}
    secrets: inherit
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
