name: OpenSSF Scorecard

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - build-image.sh
      - '.github/workflows/**'
      - '.golangci.yml'
      - '.trivyignore.yaml'
  schedule:
    - cron: "00 06 * * 1"

permissions:
  contents: read

jobs:
  analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: upcloud-tools/gha-actions/.github/workflows/scorecard.yaml@1dd7497095dbde7e8ae1b5f2afdad0a388821b74
    secrets: inherit
