name: UpCloud CSI driver e2e test

on:
  workflow_dispatch:
    inputs:
      run_1_31:
        type: boolean
        description: Run tests on k8s 1.31
        default: true
      run_1_32:
        type: boolean
        description: Run tests on k8s 1.32
        default: true
      run_1_33:
        type: boolean
        description: Run tests on k8s 1.33
        default: true
      run_1_34:
        type: boolean
        description: Run tests on k8s 1.34
        default: true
      run_1_35:
        type: boolean
        description: Run tests on k8s 1.35
        default: true
      image_tag:
        type: string
        description: "Image tag to test (default: image built from this commit)"
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: read

jobs:
  build-image:
    uses: ./.github/workflows/_reusable-build.yaml
    with:
      tags: ${{ github.sha }}
    secrets: inherit

  e2e-1-31:
    if: ${{ inputs.run_1_31 }}
    needs: build-image
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.31"
      image_tag: ${{ inputs.image_tag || github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_31 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_31 }}

  e2e-1-32:
    if: ${{ inputs.run_1_32 }}
    needs: build-image
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.32"
      image_tag: ${{ inputs.image_tag || github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_32 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_32 }}

  e2e-1-33:
    if: ${{ inputs.run_1_33 }}
    needs: build-image
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.33"
      image_tag: ${{ inputs.image_tag || github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_33 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_33 }}

  e2e-1-34:
    if: ${{ inputs.run_1_34 }}
    needs: build-image
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.34"
      image_tag: ${{ inputs.image_tag || github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_34 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_34 }}

  e2e-1-35:
    if: ${{ inputs.run_1_35 }}
    needs: build-image
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      k8s_version: "1.35"
      image_tag: ${{ inputs.image_tag || github.sha }}
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_1_35 }}
      UPCLOUD_TOKEN: ${{ secrets.UPCLOUD_TOKEN }}
      UPCLOUD_KUBERNETES_CLUSTER_ID: ${{ secrets.CLUSTER_ID_1_35 }}
