name: UpCloud CSI driver test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - '.github/workflows/test.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - '.github/workflows/test.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Install filesystem tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq xfsprogs
          sudo modprobe xfs || true

      - name: Test Driver
        run: sudo make test
