name: UpCloud CSI driver e2e test
on:
  workflow_dispatch:

permissions:
  contents: read

env:
  GO_VERSION: '1.26'

jobs:
  build-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_reusable-build.yaml
    with:
      tags: ${{ github.sha }}
    secrets: inherit

  e2e:
    needs: build-image
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      image_tag: ${{ github.sha }}
    secrets: inherit
