name: UpCloud CSI driver test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - '.github/workflows/test.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - '.github/workflows/test.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: upcloud-tools/gha-actions/.github/workflows/test-go.yaml@070918b27e20a6bd320cc93b569d912b1a227a6c
    with:
      pre_test_commands: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq xfsprogs
        sudo modprobe xfs || true
      test_command: sudo make test
