name: Trivy Scan

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - build-image.sh
      - '.github/workflows/trivy-scan.yaml'
      - '.trivyignore.yaml'
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - build-image.sh
      - '.github/workflows/trivy-scan.yaml'
      - '.trivyignore.yaml'
  schedule:
    - cron: '5 5 * * 2'

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      contents: read
      actions: read
      security-events: write
      packages: read
    uses: upcloud-tools/gha-actions/.github/workflows/trivy.yaml@070918b27e20a6bd320cc93b569d912b1a227a6c
    with:
      image_repo: upcloud-csi
    secrets: inherit
